# -------------------------------------------------------------------------------------
# ----------------------------------- XcodeGen ----------------------------------------
# -------------------------------------------------------------------------------------
#
# Generates DaisyMobileCompanion.xcodeproj from this spec.
# Run: xcodegen generate
#
# This replaces the need for a checked-in .xcodeproj — the project is
# generated fresh in CI and locally. Keep .xcodeproj in .gitignore.

name: DaisyMobileCompanion

options:
  bundleIdPrefix: com.daisy
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

# -------------------------------------------------------------------------------------
# ----------------------------------- Configs -----------------------------------------
# -------------------------------------------------------------------------------------

configs:
  Debug: debug
  Release: release

# -------------------------------------------------------------------------------------
# ----------------------------------- Targets -----------------------------------------
# -------------------------------------------------------------------------------------

targets:

  # -----------------------------------------------------------------------------------
  # ------------------------------------ App ------------------------------------------
  # -----------------------------------------------------------------------------------

  DaisyMobileCompanion:
    type: application
    platform: iOS
    sources:
      - path: DaisyMobileCompanion
        excludes:
          - "**/*Tests*"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.daisy.mobile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: "Daisy"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "$(FASTLANE_TEAM_ID)"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: true
        ENABLE_PREVIEWS: true
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: "wholemodule"

  # -----------------------------------------------------------------------------------
  # ----------------------------------- Tests -----------------------------------------
  # -----------------------------------------------------------------------------------

  DaisyMobileCompanionTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DaisyMobileCompanionTests
    dependencies:
      - target: DaisyMobileCompanion
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.daisy.mobile.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/DaisyMobileCompanion.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/DaisyMobileCompanion"
        BUNDLE_LOADER: "$(TEST_HOST)"

# -------------------------------------------------------------------------------------
# ----------------------------------- Schemes -----------------------------------------
# -------------------------------------------------------------------------------------

schemes:
  DaisyMobileCompanion:
    build:
      targets:
        DaisyMobileCompanion: all
        DaisyMobileCompanionTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - DaisyMobileCompanionTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  DaisyMobileCompanionTests:
    build:
      targets:
        DaisyMobileCompanion: all
        DaisyMobileCompanionTests: [test]
    test:
      config: Debug
      targets:
        - DaisyMobileCompanionTests
